#!/usr/bin/env node

var fileWithLineNumber = process.argv[2];
var file = fileWithLineNumber.substr(0, fileWithLineNumber.indexOf(':'));
var exec = require('child_process').exec

exec("mocha " + file, function(err, stdout, stderr) {
  console.log(stdout);
  console.log(stderr);
});
